version: "3.3"
services:
  the-forest-dedicated-server:
    container_name: TheForest
    build: .
    ports:
      - 8766:8766/tcp
      - 8766:8766/udp
      - 27015:27015/tcp
      - 27015:27015/udp
      - 27016:27016/tcp
      - 27016:27016/udp
    volumes:
      - /srv/tfds/steamcmd:/steamcmd
      - /srv/tfds/game:/theforest

#networks:
#  default:
#    external:
#      name: localdev
